# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\43926\Desktop\my_Eric\ATP_New\ATP_Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 950)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1181, 921))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1161, 821))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.g_excel = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.g_excel.setObjectName("g_excel")
        self.horizontalLayout_5.addWidget(self.g_excel)
        self.r_excel = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.r_excel.setObjectName("r_excel")
        self.horizontalLayout_5.addWidget(self.r_excel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 364, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 140, 430))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cB_model_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_1.setEnabled(True)
        self.cB_model_1.setObjectName("cB_model_1")
        self.verticalLayout_6.addWidget(self.cB_model_1)
        self.cB_model_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_2.setObjectName("cB_model_2")
        self.verticalLayout_6.addWidget(self.cB_model_2)
        self.cB_model_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_3.setObjectName("cB_model_3")
        self.verticalLayout_6.addWidget(self.cB_model_3)
        self.cB_model_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_4.setObjectName("cB_model_4")
        self.verticalLayout_6.addWidget(self.cB_model_4)
        self.cB_model_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_5.setObjectName("cB_model_5")
        self.verticalLayout_6.addWidget(self.cB_model_5)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.cB_model_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_7.setObjectName("cB_model_7")
        self.verticalLayout_6.addWidget(self.cB_model_7)
        self.cB_model_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_8.setObjectName("cB_model_8")
        self.verticalLayout_6.addWidget(self.cB_model_8)
        self.cB_model_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cB_model_9.setObjectName("cB_model_9")
        self.verticalLayout_6.addWidget(self.cB_model_9)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.scrollArea)
        self.all_model = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_model.sizePolicy().hasHeightForWidth())
        self.all_model.setSizePolicy(sizePolicy)
        self.all_model.setObjectName("all_model")
        self.horizontalLayout_7.addWidget(self.all_model, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.times_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.times_le.sizePolicy().hasHeightForWidth())
        self.times_le.setSizePolicy(sizePolicy)
        self.times_le.setObjectName("times_le")
        self.horizontalLayout_6.addWidget(self.times_le)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1171, 811))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3, 0, QtCore.Qt.AlignTop)
        self.result_tE = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.result_tE.setObjectName("result_tE")
        self.horizontalLayout_8.addWidget(self.result_tE)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.time_start_lE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_start_lE.sizePolicy().hasHeightForWidth())
        self.time_start_lE.setSizePolicy(sizePolicy)
        self.time_start_lE.setObjectName("time_start_lE")
        self.horizontalLayout_11.addWidget(self.time_start_lE)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.time_end_lE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_end_lE.sizePolicy().hasHeightForWidth())
        self.time_end_lE.setSizePolicy(sizePolicy)
        self.time_end_lE.setObjectName("time_end_lE")
        self.horizontalLayout_11.addWidget(self.time_end_lE)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.abs_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.abs_cb.setObjectName("abs_cb")
        self.horizontalLayout_10.addWidget(self.abs_cb)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.per_lE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.per_lE.sizePolicy().hasHeightForWidth())
        self.per_lE.setSizePolicy(sizePolicy)
        self.per_lE.setObjectName("per_lE")
        self.horizontalLayout_10.addWidget(self.per_lE)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.default_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.default_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.default_btn.sizePolicy().hasHeightForWidth())
        self.default_btn.setSizePolicy(sizePolicy)
        self.default_btn.setObjectName("default_btn")
        self.horizontalLayout.addWidget(self.default_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.run_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout_2.addWidget(self.run_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.g_excel.setText(_translate("MainWindow", "生成Excel"))
        self.r_excel.setText(_translate("MainWindow", "读取Excel"))
        self.label.setText(_translate("MainWindow", "运行模式"))
        self.cB_model_1.setText(_translate("MainWindow", "模式1"))
        self.cB_model_2.setText(_translate("MainWindow", "模式2"))
        self.cB_model_3.setText(_translate("MainWindow", "模式3"))
        self.cB_model_4.setText(_translate("MainWindow", "模式4"))
        self.cB_model_5.setText(_translate("MainWindow", "模式5"))
        self.checkBox.setText(_translate("MainWindow", "模式6"))
        self.cB_model_7.setText(_translate("MainWindow", "模式7"))
        self.cB_model_8.setText(_translate("MainWindow", "模式8"))
        self.cB_model_9.setText(_translate("MainWindow", "模式9"))
        self.all_model.setText(_translate("MainWindow", "全选"))
        self.label_2.setText(_translate("MainWindow", "仿真次数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "批量仿真"))
        self.label_3.setText(_translate("MainWindow", "结果标签"))
        self.label_4.setText(_translate("MainWindow", "波形提取时间"))
        self.label_7.setText(_translate("MainWindow", "-"))
        self.abs_cb.setText(_translate("MainWindow", "取绝对值"))
        self.label_5.setText(_translate("MainWindow", "取重复仿真"))
        self.label_6.setText(_translate("MainWindow", "%最大值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "结果处理"))
        self.default_btn.setText(_translate("MainWindow", "恢复默认设置"))
        self.run_btn.setText(_translate("MainWindow", "运行"))
        self.cancel_btn.setText(_translate("MainWindow", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

